services:
    vscode:
        container_name: vscode-dev
        image: codercom/code-server:latest
        ports:
            - 80:80
        volumes:
            - ./init.sh:/init.sh
            - ./ext-users-api:/app/ext-users-api
        entrypoint: ["/bin/sh", "-c", "/init.sh"]